#!/usr/bin/env node
/**
 * Offline tests for the safety guard of the daily route update (scripts/lib/guard.js).
 *
 *   node scripts/test-guard.js
 *
 * No network, no environment variables, no fixture files: every "PDF" is generated here from the airport
 * registry in data.js (synthetic routes, the real PDF's layout). The command-line cases write real PDFs with
 * a minimal PDF writer and need `pdftotext` (poppler-utils), exactly like the daily workflow.
 * Each case runs on a temporary copy of data.js / index.html / README.md / auto-added-airports.json.
 */
'use strict';
const { spawnSync } = require('node:child_process');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { loadData } = require('./lib/datajs-insert');
const S = require('./lib/airport-sources');
const G = require('./lib/guard');
const { main } = require('./update-routes-from-pdf');

const REPO = path.resolve(__dirname, '..');
const SCRIPT = path.join(__dirname, 'update-routes-from-pdf.js');
const FILES = ['data.js', 'index.html', 'README.md', 'auto-added-airports.json'];
const RAW_BLOCK_RE = /    const rawFlightData = `[^`]*`/s;
const PREV_DATE = '2026-10-01';
const PDF_DATE = '2026-10-02';
const NOW = Date.parse(`${PDF_DATE}T13:00:00Z`);

let failures = 0;
const check = (label, cond, extra = '') => { if (!cond) failures++; console.log(`  ${cond ? 'PASS' : 'FAIL'}  ${label}${extra ? ' :: ' + extra : ''}`); };
const sha = (buf) => crypto.createHash('sha256').update(buf).digest('hex');

// ------------------------------------------------------------------ synthetic data
const registry = loadData(fs.readFileSync(path.join(REPO, 'data.js'), 'utf8'));
// ASCII names without brackets (no London / alias special cases): ~150 airports
const NAMES = Object.keys(registry.airportCodes).filter((n) => /^[A-Za-z][A-Za-z .'-]*$/.test(n)).sort((a, b) => a.localeCompare(b));
if (NAMES.length < 150) throw new Error(`test-guard needs >= 150 plain airport names in data.js, found ${NAMES.length}`);
/** n departures x k arrivals, deterministic, sorted like data.js. */
function makeRoutes(departures = 140, perDeparture = 7) {
    const out = new Set();
    for (let a = 0; a < departures; a++) for (let k = 1; k <= perDeparture; k++) out.add(`${NAMES[a]} - ${NAMES[(a + k * 11) % NAMES.length]}`);
    return [...out].sort((x, y) => x.localeCompare(y));
}
const BASE = makeRoutes();                                     // the "published" data: 980 routes
const TODAY = BASE.filter((_, i) => i % 20 !== 0);              // a normal day: -5%

/** The real PDF's layout (header block, 4-column rows, "Page k of M" footers); text joined like pdftotext -layout. */
function pdfText(routes, { date = PDF_DATE, rowsPerPage = 44, header = 'Departure City', lastRunLabel = 'Last run:', pages: pageFilter = null } = {}) {
    const pairs = routes.map((r) => r.split(' - '));
    const perPage = rowsPerPage * 2;
    const total = Math.max(1, Math.ceil(pairs.length / perPage));
    const col = (s, w) => s.padEnd(Math.max(w, s.length + 2));
    const pages = [];
    for (let p = 0; p < total; p++) {
        const chunk = pairs.slice(p * perPage, (p + 1) * perPage);
        const lines = p === 0 ? [
            `${col('Departure period:', 76)}${lastRunLabel}`,
            `${col(`${date} 07:00:01 - ${date} 23:59:59 (CET)`, 76)}${date} 07:00:01 (CET)`,
            '',
            'Please note: synthetic test data generated by scripts/test-guard.js.',
            'Terms & Conditions',
            ''
        ] : [];
        lines.push(`    ${col(header, 32)}${col('Arrival City', 30)}${col(header, 30)}Arrival City`);
        for (let i = 0; i < rowsPerPage; i++) {
            const l = chunk[i], r = chunk[i + rowsPerPage];
            if (!l) break;
            lines.push(r ? `${col(l[0], 27)}${col(l[1], 32)}${col(r[0], 27)}${r[1]}` : `${col(l[0], 27)}${l[1]}`);
        }
        lines.push('', `${' '.repeat(50)}Page ${p + 1} of ${total}`);
        pages.push(lines.join('\n'));
    }
    return (pageFilter ? pages.filter((_, i) => pageFilter(i, total)) : pages).join('\n\f');
}

/** Minimal PDF (Courier, one text line per row) so pdftotext -layout reproduces the columns. ASCII only. */
function textPdf(text) {
    const objs = [];
    const add = (s) => { objs.push(s); return objs.length; };
    const font = add('<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>');
    const pagesId = add(null);
    const kids = [];
    for (const page of text.split('\f')) {
        const esc = (s) => s.replace(/[\\()]/g, (c) => '\\' + c);
        const body = `BT /F1 7 Tf 9 TL 20 820 Td ${page.split('\n').map((l) => `(${esc(l)}) Tj T*`).join(' ')} ET`;
        const content = add(`<< /Length ${Buffer.byteLength(body, 'latin1')} >>\nstream\n${body}\nendstream`);
        kids.push(add(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${content} 0 R >>`));
    }
    objs[pagesId - 1] = `<< /Type /Pages /Kids [${kids.map((k) => `${k} 0 R`).join(' ')}] /Count ${kids.length} >>`;
    const catalog = add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);
    let out = '%PDF-1.4\n';
    const offsets = objs.map((o, i) => { const at = Buffer.byteLength(out, 'latin1'); out += `${i + 1} 0 obj\n${o}\nendobj\n`; return at; });
    const xref = Buffer.byteLength(out, 'latin1');
    out += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n${offsets.map((o) => `${String(o).padStart(10, '0')} 00000 n \n`).join('')}`;
    out += `trailer\n<< /Size ${objs.length + 1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
    return Buffer.from(out, 'latin1');
}

/** Temporary site copy whose data.js holds `previous` and whose index.html / README.md show PREV_DATE. */
function makeRoot(previous = BASE) {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'guard-test-'));
    for (const f of FILES) if (fs.existsSync(path.join(REPO, f))) fs.copyFileSync(path.join(REPO, f), path.join(root, f));
    const dp = path.join(root, 'data.js');
    fs.writeFileSync(dp, fs.readFileSync(dp, 'utf8').replace(RAW_BLOCK_RE, () => `    const rawFlightData = \`${previous.join('\n')}\``));
    const [y, m, d] = PREV_DATE.split('-');
    const ip = path.join(root, 'index.html');
    fs.writeFileSync(ip, fs.readFileSync(ip, 'utf8').replace(/All You Can Fly 最新空席データ（\d{4}年\d{1,2}月\d{1,2}日更新）/, `All You Can Fly 最新空席データ（${y}年${Number(m)}月${Number(d)}日更新）`));
    const rp = path.join(root, 'README.md');
    fs.writeFileSync(rp, fs.readFileSync(rp, 'utf8').replace(/## V2（\d{4}-\d{2}-\d{2}）/, `## V2（${PREV_DATE}）`));
    return root;
}
const snapshot = (root) => FILES.map((f) => (fs.existsSync(path.join(root, f)) ? sha(fs.readFileSync(path.join(root, f))) : '-')).join(',');
const routesIn = (root) => { const m = fs.readFileSync(path.join(root, 'data.js'), 'utf8').match(/const rawFlightData = `([^`]*)`/); return m[1].trim() ? m[1].trim().split('\n') : []; };

S.setFetch(() => { throw new Error('network access in test-guard'); });
const ENV = { AUTO_ADD_AIRPORTS: 'false' }; // tier-4 behaviour only; no auto-add work

/** In-process run of main() on generated PDF text. */
async function run(label, text, { previous = BASE, env = {} } = {}) {
    const root = makeRoot(previous);
    const summaryPath = path.join(root, 'summary.md');
    const before = snapshot(root);
    const lines = [];
    const realLog = console.log;
    console.log = (...a) => lines.push(a.join(' '));
    let error = null;
    try { await main(['synthetic.pdf', '--root', root], { ...ENV, GITHUB_STEP_SUMMARY: summaryPath, ...env }, { pdfText: text, now: NOW }); }
    catch (e) { error = e; } finally { console.log = realLog; }
    const out = lines.join('\n');
    const r = { root, error, out, summary: fs.existsSync(summaryPath) ? fs.readFileSync(summaryPath, 'utf8') : '', unchanged: snapshot(root) === before, routes: routesIn(root) };
    console.log(`\n== ${label}`);
    return r;
}
const errorLines = (r) => r.out.split('\n').filter((l) => l.startsWith('::error::'));
function refused(r, reason) {
    check('refused: GuardError thrown (CLI exit 1)', r.error instanceof G.GuardError, r.error ? r.error.message : 'no error');
    check('data.js / index.html / README.md / auto-added-airports.json untouched', r.unchanged);
    check('exactly one ::error:: line', errorLines(r).length === 1, errorLines(r)[0]);
    check(`reason: ${reason}`, new RegExp(reason).test(errorLines(r)[0] || ''), errorLines(r)[0]);
    check('job summary: refusal section with the numbers', /### ⛔ Route data NOT updated/.test(r.summary) && /\| Routes to publish \| \d+ \|/.test(r.summary) && /force_update/.test(r.summary));
}
function published(r, expectedRoutes) {
    check('accepted (no error)', !r.error, r.error && r.error.message);
    check(`data.js holds the ${expectedRoutes.length} expected routes`, JSON.stringify(r.routes) === JSON.stringify(expectedRoutes), `got ${r.routes.length}`);
    check('index.html date updated', fs.readFileSync(path.join(r.root, 'index.html'), 'utf8').includes('最新空席データ（2026年10月2日更新）'));
}

async function inProcessCases() {
    const normal = await run('normal day (-5%)', pdfText(TODAY));
    published(normal, TODAY);
    check('summary: "Safety guard passed"', normal.summary.includes(`✅ Safety guard passed: ${TODAY.length} routes`));
    check('no ::error:: / guard warning', !errorLines(normal).length && !/::warning::Safety guard/.test(normal.out));

    refused(await run('0 routes (header and footers only)', pdfText([])), 'the PDF contains only 0 routes');
    refused(await run('half the routes, every page present (-50%)', pdfText(BASE.filter((_, i) => i % 2))), 'routes fell -50\\.0%25');
    refused(await run('cut-off PDF: last 40% of the pages missing', pdfText(TODAY, { pages: (i, n) => i < Math.ceil(n * 0.6) })), 'Page k of M');
    {
        const deps = [...new Set(TODAY.map((r) => r.split(' - ')[0]))];
        const kept = new Set(deps.slice(0, Math.floor(deps.length * 0.7)));
        const cut = TODAY.filter((r) => kept.has(r.split(' - ')[0]));
        const r = await run('list cut off upstream (consistent footers, last 30% of departure airports missing)', pdfText(cut));
        refused(r, 'departure airports fell');
        check('route drop alone (-30%) would not have caught it', (cut.length / BASE.length - 1) * 100 > -G.LIMITS.maxDropPct, `${cut.length}/${BASE.length}`);
    }
    {
        const r = await run('every row duplicated', pdfText(TODAY.flatMap((x) => [x, x])));
        published(r, TODAY);
        check('warning: duplicate rows ignored', r.out.includes(`::warning::Safety guard: the PDF lists ${TODAY.length} duplicate route row(s)`));
        check('data.js identical to the normal day', fs.readFileSync(path.join(r.root, 'data.js'), 'utf8') === fs.readFileSync(path.join(normal.root, 'data.js'), 'utf8'));
    }
    refused(await run('column headers renamed ("From")', pdfText(TODAY, { header: 'From' })), 'column headers are missing or different');
    refused(await run('"Last run:" missing', pdfText(TODAY, { lastRunLabel: 'Generated:' })), 'no "Last run:" date');
    refused(await run('no airport recognized', pdfText(TODAY.map((x) => x.split(' - ').map((c) => `Zz${c}`).join(' - ')))), 'only 0 routes would be published');
    {
        const big = TODAY.filter((r) => r.includes(NAMES[0])).length; // the hub that gets renamed
        const renamed = TODAY.map((r) => r.split(' - ').map((c) => (c === NAMES[0] ? `${c} Intl` : c)).join(' - '));
        const extra = TODAY.concat(BASE.slice(0, 60).map((r) => r.replace(/^([^-]+) - /, `${NAMES[0]} - `))).filter((v, i, a) => a.indexOf(v) === i);
        const hubbed = extra.map((r) => r.split(' - ').map((c) => (c === NAMES[0] ? `${c} Intl` : c)).join(' - '));
        refused(await run(`one large airport not recognized (${NAMES[0]} renamed, > 5% of the routes)`, pdfText(hubbed)), 'would be dropped because their airports are not recognized');
        const small = await run(`one small airport not recognized (${NAMES[0]} renamed, ${big} routes)`, pdfText(renamed));
        check(`accepted: ${big} of ${TODAY.length} routes skipped is below ${G.LIMITS.maxSkippedPct}%`, !small.error && big / TODAY.length * 100 <= G.LIMITS.maxSkippedPct, small.error && small.error.message);
        check('tier-4 warning still printed', /::warning::Unrecognized airport\(s\) skipped/.test(small.out));
    }
    {
        const half = BASE.filter((_, i) => i % 2);
        const r = await run('FORCE_UPDATE=true on the -50% PDF', pdfText(half), { env: { FORCE_UPDATE: 'true' } });
        published(r, half);
        check('::warning:: force_update line, no ::error::', /::warning::force_update: publishing although the safety guard failed: routes fell/.test(r.out) && !errorLines(r).length);
        check('job summary shows that force_update was used', /### ⚠️ force_update was used/.test(r.summary));
        const r2 = await run('FORCE_UPDATE=true on a normal day', pdfText(TODAY), { env: { FORCE_UPDATE: 'true' } });
        check('accepted, summary says force_update was not needed', !r2.error && /force_update was set but not needed/.test(r2.summary));
        const r3 = await run('FORCE_UPDATE=false (scheduled runs) on the -50% PDF', pdfText(half), { env: { FORCE_UPDATE: 'false' } });
        check('still refused', r3.error instanceof G.GuardError && r3.unchanged);
    }
    {
        const doubled = BASE.concat(BASE.map((x) => x.split(' - ').reverse().join(' - '))).filter((v, i, a) => a.indexOf(v) === i).sort((a, b) => a.localeCompare(b));
        refused(await run(`previous count read from data.js: same normal PDF, data.js holds ${doubled.length} routes`, pdfText(TODAY), { previous: doubled }), `routes fell .*\\(${doubled.length} -> ${TODAY.length};`);
        const empty = await run('data.js holds no routes (relative checks skipped, floor only)', pdfText(TODAY), { previous: [] });
        published(empty, TODAY);
        const rise = await run('rise +60% vs data.js (warning only)', pdfText(TODAY), { previous: TODAY.slice(0, Math.round(TODAY.length / 1.6)) });
        check('accepted with a rise warning', !rise.error && /::warning::Safety guard: routes rose \+60\.0%25/.test(rise.out), rise.error && rise.error.message);
    }
    {
        const old = await run('PDF dated before the site date (warning only)', pdfText(TODAY, { date: '2026-09-28' }));
        check('accepted with "older than the data on the site" + age warnings', !old.error && /older than the data on the site \(2026-10-01\)/.test(old.out) && /is 4 days old/.test(old.out));
    }
}

function unitCases() {
    console.log('\n== evaluate(): limits are exact');
    const m = (o) => ({ headerOk: true, pagesOk: true, lastRunDate: PDF_DATE, siteDate: PREV_DATE, today: PDF_DATE, duplicateRows: 0, parsedRoutes: 1000, candidateRoutes: 1000, routes: 1000, airports: 150, departures: 100, skippedRoutes: 0, previousRoutes: 1000, previousDepartures: 100, ...o });
    const fails = (o) => G.evaluate(m(o)).failures.length > 0;
    check('-45.0% routes passes, -45.1% fails', !fails({ routes: 550, parsedRoutes: 550, candidateRoutes: 550 }) && fails({ routes: 549, parsedRoutes: 549, candidateRoutes: 549 }));
    check('-20.0% departure airports passes, -21% fails', !fails({ departures: 80 }) && fails({ departures: 79 }));
    check('5.0% skipped passes, 5.1% fails', !fails({ routes: 950, skippedRoutes: 50 }) && fails({ routes: 949, skippedRoutes: 51 }));
    check('300 routes / 100 airports pass, 299 / 99 fail', !fails({ routes: 300, parsedRoutes: 300, candidateRoutes: 300, previousRoutes: 300 }) && fails({ routes: 299, parsedRoutes: 299, candidateRoutes: 299, previousRoutes: 299 }) && fails({ airports: 99 }));
    check('previous below 300 routes: no relative checks', !fails({ routes: 300, parsedRoutes: 300, candidateRoutes: 300, departures: 10, previousRoutes: 299, previousDepartures: 100 }));
    check('page footers: complete / last page missing / page twice', G.pagesComplete('Page 1 of 2\nPage 2 of 2') && !G.pagesComplete('Page 1 of 2') && !G.pagesComplete('Page 1 of 2\nPage 1 of 2') && !G.pagesComplete(''));
}

function cli(label, pdfBuffer, previous = BASE, env = {}) {
    const root = makeRoot(previous);
    const pdf = path.join(root, 'aycf-availability.pdf');
    fs.writeFileSync(pdf, pdfBuffer);
    const before = snapshot(root);
    const r = spawnSync(process.execPath, [SCRIPT, pdf, '--root', root], { encoding: 'utf8', env: { PATH: process.env.PATH, ...ENV, GITHUB_STEP_SUMMARY: path.join(root, 'summary.md'), ...env } });
    console.log(`\n== CLI: ${label}`);
    return { status: r.status, stdout: r.stdout, stderr: r.stderr, unchanged: snapshot(root) === before, routes: routesIn(root), summary: fs.existsSync(path.join(root, 'summary.md')) ? fs.readFileSync(path.join(root, 'summary.md'), 'utf8') : '' };
}

function cliCases() {
    if (spawnSync('pdftotext', ['-v'], { encoding: 'utf8' }).error) { check('pdftotext (poppler-utils) is installed', false); return; }
    const good = cli('normal PDF', textPdf(pdfText(TODAY)));
    check('exit 0, data.js updated', good.status === 0 && JSON.stringify(good.routes) === JSON.stringify(TODAY), `exit ${good.status}: ${good.stderr.slice(0, 200)}`);
    const zero = cli('PDF with 0 routes', textPdf(pdfText([])));
    check('exit 1, nothing written', zero.status === 1 && zero.unchanged, `exit ${zero.status}`);
    check('::error:: on stdout, no stack trace on stderr', /^::error::Route data NOT updated/m.test(zero.stdout) && !/\n\s+at /.test(zero.stderr), zero.stderr.slice(0, 200));
    check('job summary written', /### ⛔ Route data NOT updated/.test(zero.summary));
    const half = cli('PDF with half the routes', textPdf(pdfText(BASE.filter((_, i) => i % 2))));
    check('exit 1, nothing written', half.status === 1 && half.unchanged, `exit ${half.status}`);
    const forced = cli('PDF with half the routes, FORCE_UPDATE=true', textPdf(pdfText(BASE.filter((_, i) => i % 2))), BASE, { FORCE_UPDATE: 'true' });
    check('exit 0, data.js updated', forced.status === 0 && forced.routes.length === BASE.length / 2, `exit ${forced.status}`);
    const full = textPdf(pdfText(TODAY));
    for (const [what, buf] of [['empty file', Buffer.alloc(0)], ['HTML page saved as .pdf', Buffer.from('<!DOCTYPE html><html><head><title>Service Unavailable</title></head><body>503</body></html>\n')], ['PDF cut off at 60% of its bytes', full.subarray(0, Math.floor(full.length * 0.6))]]) {
        const r = cli(`unreadable input: ${what}`, buf);
        check('exit 1, nothing written', r.status === 1 && r.unchanged, `exit ${r.status}`);
        // poppler versions differ in what they salvage from a damaged file: either pdftotext fails ("not a
        // readable PDF") or the guard refuses what it extracted; both must end in one ::error:: line.
        check('one ::error:: line (unreadable PDF or guard refusal), no stack trace', (r.stdout.match(/^::error::Route data NOT updated/gm) || []).length === 1 && !/\n\s+at /.test(r.stderr), (r.stdout.match(/^::error::.*$/m) || [''])[0].slice(0, 160));
    }
}

function workflowCases() {
    console.log('\n== workflow wiring');
    const upd = fs.readFileSync(path.join(REPO, '.github/workflows/update-routes.yml'), 'utf8');
    const stat = fs.readFileSync(path.join(REPO, '.github/workflows/static.yml'), 'utf8');
    check('update-routes.yml: workflow_dispatch input force_update (boolean, default false)', /\n      force_update:\n(?:        .*\n)*?        type: boolean\n        default: false/.test(upd));
    check('update-routes.yml: FORCE_UPDATE can only be true for a manual run', upd.includes("FORCE_UPDATE: ${{ github.event_name == 'workflow_dispatch' && inputs.force_update }}"));
    const commit = upd.slice(upd.indexOf('- name: Commit and push changes'));
    check('update-routes.yml: the commit step has no if: (skipped when the update step fails)', commit.length > 30 && !/^\s+if:/m.test(commit.split('\n      - name:')[0]));
    check('static.yml: the workflow_run deploy needs a successful update run', stat.includes("github.event.workflow_run.conclusion == 'success'"));
}

(async () => {
    console.log(`synthetic data: ${BASE.length} published routes, ${TODAY.length} on the normal day, ${NAMES.length} airport names`);
    unitCases();
    await inProcessCases();
    cliCases();
    workflowCases();
    console.log(`\n${failures ? `FAILED: ${failures} check(s)` : 'ALL GUARD CHECKS PASSED'}`);
    process.exit(failures ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(1); });
