#!/usr/bin/env node
/**
 * Offline tests for the safety guard of the daily route update (scripts/lib/guard.js).
 *
 *   node scripts/test-guard.js
 *
 * No network, no environment variables, no fixture files: every "PDF" is generated here from the airport
 * registry in data.js (synthetic routes, the real PDF's layout). The command-line cases write real PDFs with
 * a minimal PDF writer and need `pdftotext` (poppler-utils), exactly like the daily workflow.
 * Each case runs on a temporary copy of data.js / index.html / README.md / auto-added-airports.json.
 *
 * What is covered: the HARD (numeric) checks refuse a PDF (exit 1, nothing written, one ::error:: line); the LAYOUT
 * checks (column headers, "Last run:" date, page footers) only warn, so every layout variation below is accepted with
 * a ::warning:: and publishes exactly the routes of the normal PDF, unless a hard check fails too; FORCE_UPDATE and the
 * unreadable-PDF refusal are not affected by the layout checks.
 */
'use strict';
const { spawnSync } = require('node:child_process');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { loadData } = require('./lib/datajs-insert');
const S = require('./lib/airport-sources');
const G = require('./lib/guard');
const { main } = require('./update-routes-from-pdf');

const REPO = path.resolve(__dirname, '..');
const SCRIPT = path.join(__dirname, 'update-routes-from-pdf.js');
const FILES = ['data.js', 'index.html', 'README.md', 'auto-added-airports.json'];
const RAW_BLOCK_RE = /    const rawFlightData = `[^`]*`/s;
const PREV_DATE = '2026-10-01';
const PDF_DATE = '2026-10-02';
const NOW = Date.parse(`${PDF_DATE}T13:00:00Z`);

let failures = 0, total = 0;
const check = (label, cond, extra = '') => { total++; if (!cond) failures++; console.log(`  ${cond ? 'PASS' : 'FAIL'}  ${label}${extra ? ' :: ' + extra : ''}`); };
const sha = (buf) => crypto.createHash('sha256').update(buf).digest('hex');

// ------------------------------------------------------------------ synthetic data
const registry = loadData(fs.readFileSync(path.join(REPO, 'data.js'), 'utf8'));
// ASCII names without brackets (no London / alias special cases): ~150 airports
const NAMES = Object.keys(registry.airportCodes).filter((n) => /^[A-Za-z][A-Za-z .'-]*$/.test(n)).sort((a, b) => a.localeCompare(b));
if (NAMES.length < 150) throw new Error(`test-guard needs >= 150 plain airport names in data.js, found ${NAMES.length}`);
/** n departures x k arrivals, deterministic, sorted like data.js. */
function makeRoutes(departures = 140, perDeparture = 7) {
    const out = new Set();
    for (let a = 0; a < departures; a++) for (let k = 1; k <= perDeparture; k++) out.add(`${NAMES[a]} - ${NAMES[(a + k * 11) % NAMES.length]}`);
    return [...out].sort((x, y) => x.localeCompare(y));
}
const BASE = makeRoutes();                                     // the "published" data: 980 routes
const TODAY = BASE.filter((_, i) => i % 20 !== 0);              // a normal day: -5%

/** The real PDF's layout (header block, 4-column rows, "Page k of M" footers); text joined like pdftotext -layout. */
function pdfText(routes, { date = PDF_DATE, rowsPerPage = 44, pages: pageFilter = null } = {}) {
    const pairs = routes.map((r) => r.split(' - '));
    const perPage = rowsPerPage * 2;
    const total = Math.max(1, Math.ceil(pairs.length / perPage));
    const col = (s, w) => s.padEnd(Math.max(w, s.length + 2));
    const pages = [];
    for (let p = 0; p < total; p++) {
        const chunk = pairs.slice(p * perPage, (p + 1) * perPage);
        const lines = p === 0 ? [
            `${col('Departure period:', 76)}Last run:`,
            `${col(`${date} 07:00:01 - ${date} 23:59:59 (CET)`, 76)}${date} 07:00:01 (CET)`,
            '',
            'Please note: synthetic test data generated by scripts/test-guard.js.',
            'Terms & Conditions',
            ''
        ] : [];
        lines.push(`    ${col('Departure City', 32)}${col('Arrival City', 30)}${col('Departure City', 30)}Arrival City`);
        for (let i = 0; i < rowsPerPage; i++) {
            const l = chunk[i], r = chunk[i + rowsPerPage];
            if (!l) break;
            lines.push(r ? `${col(l[0], 27)}${col(l[1], 32)}${col(r[0], 27)}${r[1]}` : `${col(l[0], 27)}${l[1]}`);
        }
        lines.push('', `${' '.repeat(50)}Page ${p + 1} of ${total}`);
        pages.push(lines.join('\n'));
    }
    return (pageFilter ? pages.filter((_, i) => pageFilter(i, total)) : pages).join('\n\f');
}

/** Minimal PDF (Courier, one text line per row) so pdftotext -layout reproduces the columns. ASCII only. */
function textPdf(text) {
    const objs = [];
    const add = (s) => { objs.push(s); return objs.length; };
    const font = add('<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>');
    const pagesId = add(null);
    const kids = [];
    for (const page of text.split('\f')) {
        const esc = (s) => s.replace(/[\\()]/g, (c) => '\\' + c);
        const body = `BT /F1 7 Tf 9 TL 20 820 Td ${page.split('\n').map((l) => `(${esc(l)}) Tj T*`).join(' ')} ET`;
        const content = add(`<< /Length ${Buffer.byteLength(body, 'latin1')} >>\nstream\n${body}\nendstream`);
        kids.push(add(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${content} 0 R >>`));
    }
    objs[pagesId - 1] = `<< /Type /Pages /Kids [${kids.map((k) => `${k} 0 R`).join(' ')}] /Count ${kids.length} >>`;
    const catalog = add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);
    let out = '%PDF-1.4\n';
    const offsets = objs.map((o, i) => { const at = Buffer.byteLength(out, 'latin1'); out += `${i + 1} 0 obj\n${o}\nendobj\n`; return at; });
    const xref = Buffer.byteLength(out, 'latin1');
    out += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n${offsets.map((o) => `${String(o).padStart(10, '0')} 00000 n \n`).join('')}`;
    out += `trailer\n<< /Size ${objs.length + 1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
    return Buffer.from(out, 'latin1');
}

// ------------------------------------------------------------------ layout variations
// Text-level changes of a generated PDF; each one changes ONE layout element (column headers, "Last run:", page footers).
const HEADER_LINE = /Departure City|Arrival City/;
const FOOTER_LINE = /Page \d+ of \d+/;
const mapLines = (re, fn) => (text) => text.split('\n').map((l) => (re.test(l) ? fn(l) : l)).join('\n');
// a dropped line keeps the page break (\f) that pdftotext puts in front of a page's first line
const dropLines = (re) => (text) => text.split('\n').flatMap((l) => (re.test(l) ? (l.startsWith('\f') ? ['\f'] : []) : [l])).join('\n');
const LAYOUT = {
    lowerHeaders: mapLines(HEADER_LINE, (l) => l.toLowerCase()),
    upperHeaders: mapLines(HEADER_LINE, (l) => l.toUpperCase()),
    fromTo: mapLines(HEADER_LINE, (l) => l.replace(/Departure City/g, 'From').replace(/Arrival City/g, 'To')),
    reworded: mapLines(HEADER_LINE, (l) => l.replace(/Departure City/g, 'Departure Airport').replace(/Arrival City/g, 'Arrival Airport')),
    noHeaders: dropLines(HEADER_LINE),
    noDepartureHeader: mapLines(HEADER_LINE, (l) => l.replace(/Departure City/g, '')),                 // "Arrival City" stays
    threeColumnHeader: mapLines(HEADER_LINE, (l) => l.replace(/ +Arrival City *$/, '')),                // 4th header cell missing
    headerMissingOnPage1: (text) => text.replace(/^.*Departure City.*\n/m, ''),                         // the other pages keep theirs
    slashFooters: (text) => text.replace(/Page (\d+) of (\d+)/g, 'Page $1/$2'),
    pageOnlyFooters: (text) => text.replace(/Page (\d+) of \d+/g, 'Page $1'),
    noFooters: dropLines(FOOTER_LINE),
    lastRunCapital: (text) => text.replace('Last run:', 'Last Run:'),
    lastRunSameLine: (text) => text.replace(/Last run:\n(.+?) {2,}(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} \(CET\))\n/, 'Last run: $2\n$1\n'),
    noLastRun: (text) => text.replace('Last run:', '').replace(/ {2,}\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} \(CET\)\n/, '\n')
};
LAYOUT.everything = (text) => LAYOUT.noFooters(LAYOUT.noLastRun(LAYOUT.lowerHeaders(text)));
// What the ::warning:: line says for each kind of difference.
const SAYS = {
    headersMissing: /column headers are missing or different \(no line with these column headers found\)/,
    headersOdd: /column headers are missing or different \(unexpected header line "[^"]+"\)/,
    footersMissing: /"Page k of M" footers do not cover every page \(no "Page k of M" footer found\)/,
    lastRun: /"Last run:" date could not be parsed, so the date line on the site \(index\.html, README\.md\) was not updated/
};
// [label, change, what the warning says, does the date line move to the PDF date?]
const LAYOUT_CASES = [
    ['lower-case column headers', LAYOUT.lowerHeaders, SAYS.headersMissing, true],
    ['upper-case column headers', LAYOUT.upperHeaders, SAYS.headersMissing, true],
    ['"From / To" instead of "Departure City / Arrival City"', LAYOUT.fromTo, SAYS.headersMissing, true],
    ['reworded column headers ("Departure Airport / Arrival Airport")', LAYOUT.reworded, SAYS.headersMissing, true],
    ['column headers missing on every page', LAYOUT.noHeaders, SAYS.headersMissing, true],
    ['"Departure City" header missing on every page ("Arrival City" stays)', LAYOUT.noDepartureHeader, SAYS.headersOdd, true],
    ['header line with a missing column', LAYOUT.threeColumnHeader, SAYS.headersOdd, true],
    ['"Page k/M" footers', LAYOUT.slashFooters, SAYS.footersMissing, true],
    ['"Page k" footers', LAYOUT.pageOnlyFooters, SAYS.footersMissing, true],
    ['no footers', LAYOUT.noFooters, SAYS.footersMissing, true],
    ['"Last Run:" capitalization', LAYOUT.lastRunCapital, SAYS.lastRun, false],
    ['the date on the same line as "Last run:"', LAYOUT.lastRunSameLine, SAYS.lastRun, false],
    ['no "Last run" line', LAYOUT.noLastRun, SAYS.lastRun, false]
];

/** Temporary site copy whose data.js holds `previous` and whose index.html / README.md show PREV_DATE. */
function makeRoot(previous = BASE) {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'guard-test-'));
    for (const f of FILES) if (fs.existsSync(path.join(REPO, f))) fs.copyFileSync(path.join(REPO, f), path.join(root, f));
    const dp = path.join(root, 'data.js');
    fs.writeFileSync(dp, fs.readFileSync(dp, 'utf8').replace(RAW_BLOCK_RE, () => `    const rawFlightData = \`${previous.join('\n')}\``));
    const [y, m, d] = PREV_DATE.split('-');
    const ip = path.join(root, 'index.html');
    fs.writeFileSync(ip, fs.readFileSync(ip, 'utf8').replace(/All You Can Fly 最新空席データ（\d{4}年\d{1,2}月\d{1,2}日更新）/, `All You Can Fly 最新空席データ（${y}年${Number(m)}月${Number(d)}日更新）`));
    const rp = path.join(root, 'README.md');
    fs.writeFileSync(rp, fs.readFileSync(rp, 'utf8').replace(/## V2（\d{4}-\d{2}-\d{2}）/, `## V2（${PREV_DATE}）`));
    return root;
}
const fileShas = (root) => FILES.map((f) => (fs.existsSync(path.join(root, f)) ? sha(fs.readFileSync(path.join(root, f))) : '-'));
const snapshot = (root) => fileShas(root).join(',');
const routesIn = (root) => { const m = fs.readFileSync(path.join(root, 'data.js'), 'utf8').match(/const rawFlightData = `([^`]*)`/); return m[1].trim() ? m[1].trim().split('\n') : []; };

S.setFetch(() => { throw new Error('network access in test-guard'); });
const ENV = { AUTO_ADD_AIRPORTS: 'false' }; // tier-4 behaviour only; no auto-add work

/** In-process run of main() on generated PDF text. */
async function run(label, text, { previous = BASE, env = {} } = {}) {
    const root = makeRoot(previous);
    const summaryPath = path.join(root, 'summary.md');
    const before = snapshot(root);
    const beforeShas = fileShas(root);
    const lines = [];
    const realLog = console.log;
    console.log = (...a) => lines.push(a.join(' '));
    let error = null;
    try { await main(['synthetic.pdf', '--root', root], { ...ENV, GITHUB_STEP_SUMMARY: summaryPath, ...env }, { pdfText: text, now: NOW }); }
    catch (e) { error = e; } finally { console.log = realLog; }
    const out = lines.join('\n');
    const r = { root, error, out, summary: fs.existsSync(summaryPath) ? fs.readFileSync(summaryPath, 'utf8') : '', unchanged: snapshot(root) === before, changed: FILES.filter((f, i) => fileShas(root)[i] !== beforeShas[i]), routes: routesIn(root) };
    console.log(`\n== ${label}`);
    return r;
}
const errorLines = (r) => r.out.split('\n').filter((l) => l.startsWith('::error::'));
function refused(r, reason) {
    check('refused: GuardError thrown (CLI exit 1)', r.error instanceof G.GuardError, r.error ? r.error.message : 'no error');
    check('data.js / index.html / README.md / auto-added-airports.json untouched', r.unchanged);
    check('exactly one ::error:: line', errorLines(r).length === 1, errorLines(r)[0]);
    check(`reason: ${reason}`, new RegExp(reason).test(errorLines(r)[0] || ''), errorLines(r)[0]);
    check('job summary: refusal section with the numbers', /### ⛔ Route data NOT updated/.test(r.summary) && /\| Routes to publish \| \d+ \|/.test(r.summary) && /force_update/.test(r.summary));
}
function published(r, expectedRoutes) {
    check('accepted (no error)', !r.error, r.error && r.error.message);
    check(`data.js holds the ${expectedRoutes.length} expected routes`, JSON.stringify(r.routes) === JSON.stringify(expectedRoutes), `got ${r.routes.length}`);
    check('index.html date updated', fs.readFileSync(path.join(r.root, 'index.html'), 'utf8').includes('最新空席データ（2026年10月2日更新）'));
}

const readFile = (r, f) => fs.readFileSync(path.join(r.root, f), 'utf8');
const layoutWarnings = (r) => r.out.split('\n').filter((l) => l.startsWith('::warning::Safety guard: PDF layout differs from the expected one: '));
/** A layout difference with plausible numbers: accepted, same routes as the normal PDF, a warning that says what differs. */
function layoutAccepted(r, normal, says, dateUpdated) {
    check('accepted (no error, nothing refused)', !r.error && !errorLines(r).length, r.error && r.error.message);
    check(`data.js byte-identical to the normal PDF's (${TODAY.length} routes)`, r.routes.length === TODAY.length && readFile(r, 'data.js') === readFile(normal, 'data.js'), `got ${r.routes.length}`);
    check('exactly one layout ::warning:: line, saying what differs', layoutWarnings(r).length === 1 && says.test(layoutWarnings(r)[0]), layoutWarnings(r)[0]);
    check('"Safety guard passed" line: layout differs, numbers plausible, update not blocked', /Safety guard passed: .*The PDF layout differs from the expected one \(.+\), but the numbers are plausible, so the update is not blocked\./.test(r.out));
    check('job summary: passed, layout section, table row "warning (not blocking)", no refusal', /✅ Safety guard passed/.test(r.summary) && /### ⚠️ PDF layout differs from the expected one/.test(r.summary)
        && /\| ⚠️ warning \(not blocking\) \|/.test(r.summary) && !/⛔/.test(r.summary));
    if (dateUpdated) check('date line moved to the PDF date (data.js, index.html, README.md written)', r.changed.join() === 'data.js,index.html,README.md' && readFile(r, 'index.html').includes('最新空席データ（2026年10月2日更新）') && readFile(r, 'README.md').includes('## V2（2026-10-02）'), r.changed.join());
    else check('date line unchanged: index.html and README.md keep 2026-10-01, only data.js written', r.changed.join() === 'data.js' && readFile(r, 'index.html').includes('最新空席データ（2026年10月1日更新）') && readFile(r, 'README.md').includes('## V2（2026-10-01）'), r.changed.join());
}

async function inProcessCases() {
    const normal = await run('normal day (-5%)', pdfText(TODAY));
    published(normal, TODAY);
    check('summary: "Safety guard passed"', normal.summary.includes(`✅ Safety guard passed: ${TODAY.length} routes`));
    check('no ::error:: / guard warning', !errorLines(normal).length && !/::warning::Safety guard/.test(normal.out));

    refused(await run('0 routes (header and footers only)', pdfText([])), 'the PDF contains only 0 routes');
    {
        const r = await run('half the routes, every page present (-50%)', pdfText(BASE.filter((_, i) => i % 2)));
        refused(r, 'routes fell -50\\.0%25');
        check('no layout hint in the ::error:: line when the layout is as expected', !/layout/.test(errorLines(r)[0] || ''), errorLines(r)[0]);
    }
    {
        // The footers only warn; it is the numeric check (departure airports fell) that refuses a large cut-off.
        const pagesTotal = Math.ceil(TODAY.length / 88), kept = Math.ceil(pagesTotal * 0.6);
        const r = await run('cut-off PDF: last 40% of the pages missing (footers incomplete)', pdfText(TODAY, { pages: (i, n) => i < Math.ceil(n * 0.6) }));
        refused(r, 'departure airports fell');
        check('::error:: names the incomplete page footers as a likely cause', /; the PDF layout also differs from the expected one \(page footers\), which may be the cause\./.test(errorLines(r)[0] || ''), errorLines(r)[0]);
        check('the footers are also printed as a ::warning:: (what was found)', layoutWarnings(r).length === 1 && new RegExp(`${kept} "Page k of M" footer\\(s\\) found for ${pagesTotal} page\\(s\\)`).test(layoutWarnings(r)[0]), layoutWarnings(r)[0]);
        const small = await run('cut-off PDF: only the last page missing (numbers still plausible)', pdfText(TODAY, { pages: (i, n) => i < n - 1 }));
        check('accepted with the footer warning: a small cut-off is only a warning, the numeric checks decide', !small.error && layoutWarnings(small).length === 1 && new RegExp(`${pagesTotal - 1} "Page k of M" footer\\(s\\) found for ${pagesTotal} page\\(s\\)`).test(layoutWarnings(small)[0]), small.error ? small.error.message : layoutWarnings(small)[0]);
    }
    {
        const deps = [...new Set(TODAY.map((r) => r.split(' - ')[0]))];
        const kept = new Set(deps.slice(0, Math.floor(deps.length * 0.7)));
        const cut = TODAY.filter((r) => kept.has(r.split(' - ')[0]));
        const r = await run('list cut off upstream (consistent footers, last 30% of departure airports missing)', pdfText(cut));
        refused(r, 'departure airports fell');
        check('route drop alone (-30%) would not have caught it', (cut.length / BASE.length - 1) * 100 > -G.LIMITS.maxDropPct, `${cut.length}/${BASE.length}`);
    }
    {
        const r = await run('every row duplicated', pdfText(TODAY.flatMap((x) => [x, x])));
        published(r, TODAY);
        check('warning: duplicate rows ignored', r.out.includes(`::warning::Safety guard: the PDF lists ${TODAY.length} duplicate route row(s)`));
        check('data.js identical to the normal day', fs.readFileSync(path.join(r.root, 'data.js'), 'utf8') === fs.readFileSync(path.join(normal.root, 'data.js'), 'utf8'));
    }
    // Layout differences are warnings: with plausible numbers each one is accepted and publishes the normal PDF's routes.
    for (const [name, change, says, dateUpdated] of LAYOUT_CASES) {
        layoutAccepted(await run(`layout differs: ${name}`, change(pdfText(TODAY))), normal, says, dateUpdated);
    }
    {
        const r = await run('layout differs: all three at once (lower-case headers, no footers, no "Last run" line)', LAYOUT.everything(pdfText(TODAY)));
        check('accepted, data.js byte-identical to the normal PDF\'s', !r.error && readFile(r, 'data.js') === readFile(normal, 'data.js'));
        check('three layout ::warning:: lines, one per difference', layoutWarnings(r).length === 3 && SAYS.headersMissing.test(layoutWarnings(r)[0]) && SAYS.lastRun.test(layoutWarnings(r)[1]) && SAYS.footersMissing.test(layoutWarnings(r)[2]), layoutWarnings(r).join(' | '));
        check('job summary: three "warning (not blocking)" rows', (r.summary.match(/\| ⚠️ warning \(not blocking\) \|/g) || []).length === 3);
        check('only data.js written (no "Last run" date to put on the site)', r.changed.join() === 'data.js', r.changed.join());
    }
    {
        const r = await run('column header missing on page 1 only (the other pages keep theirs)', LAYOUT.headerMissingOnPage1(pdfText(TODAY)));
        published(r, TODAY);
        check('accepted without a layout warning: only the header lines that exist are compared with the expected shape (a page without one is not detected)', !layoutWarnings(r).length && readFile(r, 'data.js') === readFile(normal, 'data.js'));
    }
    refused(await run('no airport recognized', pdfText(TODAY.map((x) => x.split(' - ').map((c) => `Zz${c}`).join(' - ')))), 'only 0 routes would be published');
    {
        // A layout difference never fails the run by itself, but together with a failed hard check it is still refused (exit 1, nothing written).
        const half = BASE.filter((_, i) => i % 2);
        const depsAll = [...new Set(TODAY.map((r) => r.split(' - ')[0]))];
        const keptDeps = new Set(depsAll.slice(0, Math.floor(depsAll.length * 0.7)));
        const hubbed = TODAY.concat(BASE.slice(0, 60).map((r) => r.replace(/^([^-]+) - /, `${NAMES[0]} - `))).filter((v, i, a) => a.indexOf(v) === i)
            .map((r) => r.split(' - ').map((c) => (c === NAMES[0] ? `${c} Intl` : c)).join(' - '));
        const nothingKnown = TODAY.map((x) => x.split(' - ').map((c) => `Zz${c}`).join(' - '));
        for (const [what, routes, reason] of [
            ['only 200 routes (minimum 300)', TODAY.slice(0, 200), 'the PDF contains only 20[01] routes'], // a lower-case header row adds one unrecognized pseudo-route
            ['half the routes (-50%)', half, 'routes fell -50\\.0%25'],
            ['30% of the departure airports missing', TODAY.filter((r) => keptDeps.has(r.split(' - ')[0])), 'departure airports fell'],
            ['one large airport not recognized (> 5% of the routes)', hubbed, 'would be dropped because their airports are not recognized'],
            ['no airport recognized', nothingKnown, 'only 0 routes would be published']
        ]) {
            const r = await run(`layout differs (all three) AND ${what}`, LAYOUT.everything(pdfText(routes)));
            refused(r, reason);
            check('::error:: names the three layout differences as a likely cause', /; the PDF layout also differs from the expected one \(column headers, "Last run:" date, page footers\), which may be the cause\. If this change is real/.test(errorLines(r)[0] || ''), errorLines(r)[0]);
            check('the three layout differences are also printed as ::warning:: lines', layoutWarnings(r).length === 3);
            check('summary table: layout rows are warnings, the failed hard check is FAILED', (r.summary.match(/\| ⚠️ warning \(not blocking\) \|/g) || []).length === 3 && /\*\*FAILED\*\*/.test(r.summary));
        }
        const one = await run('page footers differ (none) AND half the routes (-50%)', LAYOUT.noFooters(pdfText(half)));
        refused(one, 'routes fell -50\\.0%25');
        check('::error:: names only the footers', /\(page footers\), which may be the cause\./.test(errorLines(one)[0] || ''), errorLines(one)[0]);
    }
    {
        const big = TODAY.filter((r) => r.includes(NAMES[0])).length; // the hub that gets renamed
        const renamed = TODAY.map((r) => r.split(' - ').map((c) => (c === NAMES[0] ? `${c} Intl` : c)).join(' - '));
        const extra = TODAY.concat(BASE.slice(0, 60).map((r) => r.replace(/^([^-]+) - /, `${NAMES[0]} - `))).filter((v, i, a) => a.indexOf(v) === i);
        const hubbed = extra.map((r) => r.split(' - ').map((c) => (c === NAMES[0] ? `${c} Intl` : c)).join(' - '));
        refused(await run(`one large airport not recognized (${NAMES[0]} renamed, > 5% of the routes)`, pdfText(hubbed)), 'would be dropped because their airports are not recognized');
        const small = await run(`one small airport not recognized (${NAMES[0]} renamed, ${big} routes)`, pdfText(renamed));
        check(`accepted: ${big} of ${TODAY.length} routes skipped is below ${G.LIMITS.maxSkippedPct}%`, !small.error && big / TODAY.length * 100 <= G.LIMITS.maxSkippedPct, small.error && small.error.message);
        check('tier-4 warning still printed', /::warning::Unrecognized airport\(s\) skipped/.test(small.out));
    }
    {
        const half = BASE.filter((_, i) => i % 2);
        const r = await run('FORCE_UPDATE=true on the -50% PDF', pdfText(half), { env: { FORCE_UPDATE: 'true' } });
        published(r, half);
        check('::warning:: force_update line, no ::error::', /::warning::force_update: publishing although the safety guard failed: routes fell/.test(r.out) && !errorLines(r).length);
        check('job summary shows that force_update was used', /### ⚠️ force_update was used/.test(r.summary));
        const r2 = await run('FORCE_UPDATE=true on a normal day', pdfText(TODAY), { env: { FORCE_UPDATE: 'true' } });
        check('accepted, summary says force_update was not needed', !r2.error && /force_update was set but not needed/.test(r2.summary));
        const r3 = await run('FORCE_UPDATE=false (scheduled runs) on the -50% PDF', pdfText(half), { env: { FORCE_UPDATE: 'false' } });
        check('still refused', r3.error instanceof G.GuardError && r3.unchanged);
        const lay = await run('FORCE_UPDATE=true on a layout-only difference (lower-case headers)', LAYOUT.lowerHeaders(pdfText(TODAY)), { env: { FORCE_UPDATE: 'true' } });
        check('accepted, force_update was not needed, the layout is still reported as a warning', !lay.error && /force_update was set but not needed/.test(lay.summary) && layoutWarnings(lay).length === 1);
        const both = await run('FORCE_UPDATE=true on layout differences AND the -50% PDF', LAYOUT.everything(pdfText(half)), { env: { FORCE_UPDATE: 'true' } });
        check('published although both failed: no ::error::, data.js holds the half', !both.error && !errorLines(both).length && JSON.stringify(both.routes) === JSON.stringify(half), both.error && both.error.message);
        const forceLine = both.out.split('\n').find((l) => l.startsWith('::warning::force_update: publishing although the safety guard failed: routes fell')) || '';
        check('::warning:: force_update line carries no layout hint; the three layout differences are separate ::warning:: lines', forceLine !== '' && !/layout/.test(forceLine) && layoutWarnings(both).length === 3, forceLine);
        check('job summary shows that force_update was used; only data.js written', /### ⚠️ force_update was used/.test(both.summary) && both.changed.join() === 'data.js', both.changed.join());
        const notForced = await run('FORCE_UPDATE=false on layout differences AND the -50% PDF', LAYOUT.everything(pdfText(half)), { env: { FORCE_UPDATE: 'false' } });
        check('still refused, nothing written', notForced.error instanceof G.GuardError && notForced.unchanged);
    }
    {
        const doubled = BASE.concat(BASE.map((x) => x.split(' - ').reverse().join(' - '))).filter((v, i, a) => a.indexOf(v) === i).sort((a, b) => a.localeCompare(b));
        refused(await run(`previous count read from data.js: same normal PDF, data.js holds ${doubled.length} routes`, pdfText(TODAY), { previous: doubled }), `routes fell .*\\(${doubled.length} -> ${TODAY.length};`);
        const empty = await run('data.js holds no routes (relative checks skipped, floor only)', pdfText(TODAY), { previous: [] });
        published(empty, TODAY);
        const rise = await run('rise +60% vs data.js (warning only)', pdfText(TODAY), { previous: TODAY.slice(0, Math.round(TODAY.length / 1.6)) });
        check('accepted with a rise warning', !rise.error && /::warning::Safety guard: routes rose \+60\.0%25/.test(rise.out), rise.error && rise.error.message);
    }
    {
        const old = await run('PDF dated before the site date (warning only)', pdfText(TODAY, { date: '2026-09-28' }));
        check('accepted with "older than the data on the site" + age warnings', !old.error && /older than the data on the site \(2026-10-01\)/.test(old.out) && /is 4 days old/.test(old.out));
    }
}

function unitCases() {
    console.log('\n== evaluate(): limits are exact');
    const m = (o) => ({ headerOk: true, pagesOk: true, lastRunDate: PDF_DATE, siteDate: PREV_DATE, today: PDF_DATE, duplicateRows: 0, parsedRoutes: 1000, candidateRoutes: 1000, routes: 1000, airports: 150, departures: 100, skippedRoutes: 0, previousRoutes: 1000, previousDepartures: 100, ...o });
    const fails = (o) => G.evaluate(m(o)).failures.length > 0;
    check('-45.0% routes passes, -45.1% fails', !fails({ routes: 550, parsedRoutes: 550, candidateRoutes: 550 }) && fails({ routes: 549, parsedRoutes: 549, candidateRoutes: 549 }));
    check('-20.0% departure airports passes, -21% fails', !fails({ departures: 80 }) && fails({ departures: 79 }));
    check('5.0% skipped passes, 5.1% fails', !fails({ routes: 950, skippedRoutes: 50 }) && fails({ routes: 949, skippedRoutes: 51 }));
    check('300 routes / 100 airports pass, 299 / 99 fail', !fails({ routes: 300, parsedRoutes: 300, candidateRoutes: 300, previousRoutes: 300 }) && fails({ routes: 299, parsedRoutes: 299, candidateRoutes: 299, previousRoutes: 299 }) && fails({ airports: 99 }));
    check('previous below 300 routes: no relative checks', !fails({ routes: 300, parsedRoutes: 300, candidateRoutes: 300, departures: 10, previousRoutes: 299, previousDepartures: 100 }));
    check('page footers: complete / last page missing / page twice', G.pagesComplete('Page 1 of 2\nPage 2 of 2') && !G.pagesComplete('Page 1 of 2') && !G.pagesComplete('Page 1 of 2\nPage 1 of 2') && !G.pagesComplete(''));

    console.log('\n== evaluate(): layout differences are warnings, never failures; hard thresholds do not depend on them');
    const bad = { headerOk: false, pagesOk: false, lastRunDate: null };
    const lay = G.evaluate(m(bad));
    check('three layout differences: no failure, three warnings, three names', lay.failures.length === 0 && lay.warnings.length === 3 && lay.layout.join(' | ') === 'column headers | "Last run:" date | page footers', JSON.stringify(lay.layout));
    check('layout rows stay in the table as not-ok rows flagged layout: true', lay.checks.filter((c) => c.layout).length === 3 && lay.checks.filter((c) => c.layout && !c.ok).length === 3 && lay.checks.filter((c) => !c.layout).every((c) => c.ok));
    check('a normal verdict has no layout difference and no warning', G.evaluate(m({})).layout.length === 0 && G.evaluate(m({})).warnings.length === 0);
    const failsBad = (o) => fails({ ...bad, ...o });
    check('with all layout checks failing: -45.0% routes passes, -45.1% fails', !failsBad({ routes: 550, parsedRoutes: 550, candidateRoutes: 550 }) && failsBad({ routes: 549, parsedRoutes: 549, candidateRoutes: 549 }));
    check('with all layout checks failing: -20.0% departure airports passes, -21% fails', !failsBad({ departures: 80 }) && failsBad({ departures: 79 }));
    check('with all layout checks failing: 5.0% skipped passes, 5.1% fails', !failsBad({ routes: 950, skippedRoutes: 50 }) && failsBad({ routes: 949, skippedRoutes: 51 }));
    check('with all layout checks failing: 300 routes / 100 airports pass, 299 / 99 fail', !failsBad({ routes: 300, parsedRoutes: 300, candidateRoutes: 300, previousRoutes: 300 }) && failsBad({ routes: 299, parsedRoutes: 299, candidateRoutes: 299, previousRoutes: 299 }) && failsBad({ airports: 99 }));
    const both = G.evaluate(m({ ...bad, routes: 299, parsedRoutes: 299, candidateRoutes: 299, previousRoutes: 299 }));
    check('layout differences + 299 routes: the failures are the numeric ones only, the layout stays a warning', both.failures.length === 2 && both.failures.every((f) => /only 299 routes/.test(f)) && both.layout.length === 3 && both.warnings.length >= 3, JSON.stringify(both.failures));
    check('the "Last run:" warning says the date line was not updated', /"Last run:" date could not be parsed, so the date line on the site \(index\.html, README\.md\) was not updated/.test(lay.warnings[1]), lay.warnings[1]);
}

function cli(label, pdfBuffer, previous = BASE, env = {}) {
    const root = makeRoot(previous);
    const pdf = path.join(root, 'aycf-availability.pdf');
    fs.writeFileSync(pdf, pdfBuffer);
    const before = snapshot(root);
    const beforeShas = fileShas(root);
    const r = spawnSync(process.execPath, [SCRIPT, pdf, '--root', root], { encoding: 'utf8', env: { PATH: process.env.PATH, ...ENV, GITHUB_STEP_SUMMARY: path.join(root, 'summary.md'), ...env } });
    console.log(`\n== CLI: ${label}`);
    return { root, status: r.status, stdout: r.stdout, stderr: r.stderr, unchanged: snapshot(root) === before, changed: FILES.filter((f, i) => fileShas(root)[i] !== beforeShas[i]), routes: routesIn(root), summary: fs.existsSync(path.join(root, 'summary.md')) ? fs.readFileSync(path.join(root, 'summary.md'), 'utf8') : '' };
}

function cliCases() {
    if (spawnSync('pdftotext', ['-v'], { encoding: 'utf8' }).error) { check('pdftotext (poppler-utils) is installed', false); return; }
    const good = cli('normal PDF', textPdf(pdfText(TODAY)));
    check('exit 0, data.js updated', good.status === 0 && JSON.stringify(good.routes) === JSON.stringify(TODAY), `exit ${good.status}: ${good.stderr.slice(0, 200)}`);
    const zero = cli('PDF with 0 routes', textPdf(pdfText([])));
    check('exit 1, nothing written', zero.status === 1 && zero.unchanged, `exit ${zero.status}`);
    check('::error:: on stdout, no stack trace on stderr', /^::error::Route data NOT updated/m.test(zero.stdout) && !/\n\s+at /.test(zero.stderr), zero.stderr.slice(0, 200));
    check('job summary written', /### ⛔ Route data NOT updated/.test(zero.summary));
    const half = cli('PDF with half the routes', textPdf(pdfText(BASE.filter((_, i) => i % 2))));
    check('exit 1, nothing written', half.status === 1 && half.unchanged, `exit ${half.status}`);
    const forced = cli('PDF with half the routes, FORCE_UPDATE=true', textPdf(pdfText(BASE.filter((_, i) => i % 2))), BASE, { FORCE_UPDATE: 'true' });
    check('exit 0, data.js updated', forced.status === 0 && forced.routes.length === BASE.length / 2, `exit ${forced.status}`);
    // Layout differences through the real pdftotext path: exit 0, a ::warning::, the same routes as the normal PDF.
    for (const [what, change, says, dateUpdated] of [['lower-case column headers', LAYOUT.lowerHeaders, SAYS.headersMissing, true], ['column headers missing on every page', LAYOUT.noHeaders, SAYS.headersMissing, true], ['no page footers', LAYOUT.noFooters, SAYS.footersMissing, true], ['"Last Run:" capitalization', LAYOUT.lastRunCapital, SAYS.lastRun, false]]) {
        const r = cli(`layout differs: ${what}`, textPdf(change(pdfText(TODAY))));
        check('exit 0, data.js holds the same routes as the normal PDF', r.status === 0 && JSON.stringify(r.routes) === JSON.stringify(TODAY), `exit ${r.status}: ${r.stderr.slice(0, 200)}`);
        const w = r.stdout.split('\n').filter((l) => l.startsWith('::warning::Safety guard: PDF layout differs from the expected one: '));
        check('one layout ::warning:: line, no ::error::', w.length === 1 && says.test(w[0]) && !/^::error::/m.test(r.stdout), w[0]);
        check(dateUpdated ? 'date line updated (data.js, index.html, README.md written)' : 'date line unchanged (only data.js written)', r.changed.join() === (dateUpdated ? 'data.js,index.html,README.md' : 'data.js'), r.changed.join());
    }
    const messy = cli('layout differs (all three) AND only 200 routes', textPdf(LAYOUT.everything(pdfText(TODAY.slice(0, 200)))));
    check('exit 1, nothing written', messy.status === 1 && messy.unchanged, `exit ${messy.status}`);
    check('exactly one ::error:: line, naming the layout as a likely cause; no stack trace', (messy.stdout.match(/^::error::/gm) || []).length === 1 && /which may be the cause\./.test(messy.stdout) && !/\n\s+at /.test(messy.stderr), (messy.stdout.match(/^::error::.*$/m) || [''])[0].slice(0, 200));
    const full = textPdf(pdfText(TODAY));
    const html = Buffer.from('<!DOCTYPE html><html><head><title>Service Unavailable</title></head><body>503</body></html>\n');
    for (const [what, buf] of [['empty file', Buffer.alloc(0)], ['HTML page saved as .pdf', html], ['PDF cut off at 60% of its bytes', full.subarray(0, Math.floor(full.length * 0.6))]]) {
        const r = cli(`unreadable input: ${what}`, buf);
        check('exit 1, nothing written', r.status === 1 && r.unchanged, `exit ${r.status}`);
        // poppler versions differ in what they salvage from a damaged file: either pdftotext fails ("not a
        // readable PDF") or the guard refuses what it extracted; both must end in one ::error:: line.
        check('one ::error:: line (unreadable PDF or guard refusal), no stack trace', (r.stdout.match(/^::error::Route data NOT updated/gm) || []).length === 1 && !/\n\s+at /.test(r.stderr), (r.stdout.match(/^::error::.*$/m) || [''])[0].slice(0, 160));
    }
    // An unreadable download is refused even with FORCE_UPDATE=true: there is nothing to publish.
    const unreadableForced = cli('unreadable input (HTML page saved as .pdf), FORCE_UPDATE=true', html, BASE, { FORCE_UPDATE: 'true' });
    check('exit 1, nothing written, one ::error:: "not a readable PDF", no force_update warning', unreadableForced.status === 1 && unreadableForced.unchanged && (unreadableForced.stdout.match(/^::error::Route data NOT updated, the site keeps its current data: the downloaded file is not a readable PDF/gm) || []).length === 1 && !/force_update/.test(unreadableForced.stdout), unreadableForced.stdout.slice(0, 200));
}

function workflowCases() {
    console.log('\n== workflow wiring');
    const upd = fs.readFileSync(path.join(REPO, '.github/workflows/update-routes.yml'), 'utf8');
    const stat = fs.readFileSync(path.join(REPO, '.github/workflows/static.yml'), 'utf8');
    check('update-routes.yml: workflow_dispatch input force_update (boolean, default false)', /\n      force_update:\n(?:        .*\n)*?        type: boolean\n        default: false/.test(upd));
    check('update-routes.yml: FORCE_UPDATE can only be true for a manual run', upd.includes("FORCE_UPDATE: ${{ github.event_name == 'workflow_dispatch' && inputs.force_update }}"));
    const commit = upd.slice(upd.indexOf('- name: Commit and push changes'));
    check('update-routes.yml: the commit step has no if: (skipped when the update step fails)', commit.length > 30 && !/^\s+if:/m.test(commit.split('\n      - name:')[0]));
    check('static.yml: the workflow_run deploy needs a successful update run', stat.includes("github.event.workflow_run.conclusion == 'success'"));
}

(async () => {
    console.log(`synthetic data: ${BASE.length} published routes, ${TODAY.length} on the normal day, ${NAMES.length} airport names`);
    unitCases();
    await inProcessCases();
    cliCases();
    workflowCases();
    console.log(`\n${failures ? `FAILED: ${failures} of ${total} check(s)` : `ALL GUARD CHECKS PASSED (${total} checks)`}`);
    process.exit(failures ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(1); });
